#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_mp3 = env_modules.Clone()

if not env["mp3_extra_formats"] and not env["module_ffmpeg_enabled"]:
    env_mp3.Append(CPPDEFINES=["DR_MP3_ONLY_MP3"])

# Godot source files
env_mp3.add_source_files(env.modules_sources, "*.cpp")
