#!/usr/bin/env python

Import("env")
Import("env_modules")

env_opus = env_modules.Clone()

if env["builtin_opus"]:
    thirdparty_dir = "#thirdparty/opus/"

    # WebM uses only the Opus decoder. Keep encoder sources out of the build.
    thirdparty_sources = [
        "opus.c",
        "opus_decoder.c",
        "opus_multistream.c",
        "opus_multistream_decoder.c",
        "extensions.c",
        "celt/bands.c",
        "celt/celt.c",
        "celt/celt_decoder.c",
        "celt/cwrs.c",
        "celt/entcode.c",
        "celt/entdec.c",
        "celt/entenc.c",
        "celt/kiss_fft.c",
        "celt/laplace.c",
        "celt/mathops.c",
        "celt/mdct.c",
        "celt/modes.c",
        "celt/pitch.c",
        "celt/celt_lpc.c",
        "celt/quant_bands.c",
        "celt/rate.c",
        "celt/vq.c",
        "silk/CNG.c",
        "silk/code_signs.c",
        "silk/init_decoder.c",
        "silk/decode_core.c",
        "silk/decode_frame.c",
        "silk/decode_parameters.c",
        "silk/decode_indices.c",
        "silk/decode_pulses.c",
        "silk/decoder_set_fs.c",
        "silk/dec_API.c",
        "silk/NLSF2A.c",
        "silk/NLSF_decode.c",
        "silk/NLSF_unpack.c",
        "silk/LPC_analysis_filter.c",
        "silk/LPC_inv_pred_gain.c",
        "silk/LPC_fit.c",
        "silk/bwexpander.c",
        "silk/bwexpander_32.c",
        "silk/decode_pitch.c",
        "silk/gain_quant.c",
        "silk/lin2log.c",
        "silk/log2lin.c",
        "silk/NLSF_stabilize.c",
        "silk/PLC.c",
        "silk/shell_coder.c",
        "silk/tables_gain.c",
        "silk/tables_LTP.c",
        "silk/tables_NLSF_CB_NB_MB.c",
        "silk/tables_NLSF_CB_WB.c",
        "silk/tables_other.c",
        "silk/tables_pitch_lag.c",
        "silk/tables_pulses_per_block.c",
        "silk/pitch_est_tables.c",
        "silk/sort.c",
        "silk/VAD.c",
        "silk/control_audio_bandwidth.c",
        "silk/resampler.c",
        "silk/resampler_down2.c",
        "silk/resampler_down2_3.c",
        "silk/resampler_private_AR2.c",
        "silk/resampler_private_down_FIR.c",
        "silk/resampler_private_IIR_FIR.c",
        "silk/resampler_private_up2_HQ.c",
        "silk/resampler_rom.c",
        "silk/sigm_Q15.c",
        "silk/sum_sqr_shift.c",
        "silk/stereo_MS_to_LR.c",
        "silk/stereo_decode_pred.c",
        "silk/table_LSF_cos.c",
    ]

    if env["platform"] in ["android", "iphone", "javascript"]:
        env_opus.Append(CPPDEFINES=["FIXED_POINT"])

    if env["platform"] == "android":
        if "android_arch" in env and env["android_arch"] == "armv7":
            env_opus.Append(CPPDEFINES=["OPUS_ARM_OPT"])
        elif "android_arch" in env and env["android_arch"] == "arm64v8":
            env_opus.Append(CPPDEFINES=["OPUS_ARM64_OPT"])
    elif env["platform"] == "iphone":
        if "arch" in env and env["arch"] == "arm":
            env_opus.Append(CPPDEFINES=["OPUS_ARM_OPT"])
        elif "arch" in env and env["arch"] == "arm64":
            env_opus.Append(CPPDEFINES=["OPUS_ARM64_OPT"])
    elif env["platform"] == "osx" and "arch" in env and env["arch"] == "arm64":
        env_opus.Append(CPPDEFINES=["OPUS_ARM64_OPT"])

    env_opus.Append(CPPDEFINES=["HAVE_CONFIG_H"])
    env_opus.Prepend(CPPPATH=[thirdparty_dir, thirdparty_dir + "celt", thirdparty_dir + "opus", thirdparty_dir + "silk"])

    env_thirdparty = env_opus.Clone()
    env_thirdparty.disable_warnings()
    thirdparty_obj = []
    env_thirdparty.add_source_files(thirdparty_obj, [thirdparty_dir + file for file in thirdparty_sources])
    env.modules_sources += thirdparty_obj

module_obj = []
env_opus.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
env.Depends(module_obj, thirdparty_obj)
